### ISSUE TITLE
Allow configuration of tags

### ISSUE THREAD

**Issue by loevgaard** [Setono/TagBagBundle#14]
Proposed by @JulienLoison

Allow to configure the bundles as such:

```
setono_tag_bag:
    app.my_awesome_tag:
        type: Setono\TagBag\Tag\TwigTag
        template: 'tag_something.html.twig'
```

and have a corresponding Twig function to render it:

`{{ setono_tag_render('app.my_awesomme_tag') }}`
